###############################################################################
#
# Licensed to the Apache Software Foundation (ASF) under one 
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
# KIND, either express or implied.  See the License for the 
# specific language governing permissions and limitations
# under the License.
#
###############################################################################

x-logging: &logging
  logging:
    driver: json-file
    options:
      mode: non-blocking
      max-buffer-size: 100m
      max-size: 10m
      max-file: 1

services:
  wmo-resource-catalogue-backend:
    container_name: wmo-resource-catalogue-backend
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    restart: always
    environment:
      - discovery.type=single-node
      - discovery.seed_hosts=[]
      - node.name=elasticsearch-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=es-wmo-resource-catalogue
      - xpack.security.enabled=false
    mem_limit: 1.5g
    memswap_limit: 1.5g
    volumes:
      - wmo-resource-catalogue-backend-data:/usr/share/elasticsearch/data:rw
    # ulimits:
    #   nofile:
    #     soft: 524288
    #     hard: 524288
    #   memlock:
    #     soft: -1
    #     hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 5s
      retries: 100
    networks:
      - wmo-resource-catalogue-net
    <<: *logging

  wmo-resource-catalogue-prometheus:
    image: prom/prometheus
    container_name: wmo-resource-catalogue-prometheus
    volumes:
      - ./wmo-resource-catalogue-monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - wmo-resource-catalogue-net
    <<: *logging

  wmo-resource-catalogue-grafana:
    image: grafana/grafana-oss
    container_name: wmo-resource-catalogue-grafana
    env_file:
      - wmo-resource-catalogue.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 5s
      retries: 100
    networks:
      - wmo-resource-catalogue-net
    volumes:
      - ./wmo-resource-catalogue-monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_HIDE_VERSION=true
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ALERTING_ENABLED=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_DISABLE_SIGNOUT_MENU=true
      - GF_SERVER_ROOT_URL=${WMO_RESOURCE_CATALOGUE_API_URL}/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    <<: *logging

  wmo-resource-catalogue-cache:
    image: redis:latest
    container_name: wmo-resource-catalogue-cache
    env_file:
      - wmo-resource-catalogue.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 100
    networks:
      - wmo-resource-catalogue-net
    <<: *logging

  wmo-resource-catalogue-broker:
    container_name: wmo-resource-catalogue-broker
    restart: always
    build:
      context: ./wmo-resource-catalogue-broker/
    env_file:
      - wmo-resource-catalogue.env
    networks:
      - wmo-resource-catalogue-net
    <<: *logging

  wmo-resource-catalogue-metrics-collector:
    container_name: wmo-resource-catalogue-metrics-collector
    restart: unless-stopped
    build:
      context: ./wmo-resource-catalogue-monitoring/metrics-collector/
    env_file:
      - wmo-resource-catalogue.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006"]
      interval: 5s
      retries: 3
    networks:
      - wmo-resource-catalogue-net
    depends_on:
      - wmo-resource-catalogue-broker
    <<: *logging

  wmo-resource-catalogue-management:
    container_name: wmo-resource-catalogue-management
    build:
      context: ./wmo-resource-catalogue-management/
    env_file:
      - wmo-resource-catalogue.env
    environment:
      - WMO_RESOURCE_CATALOGUE_API_URL_DOCKER=http://wmo-resource-catalogue-api:8080
    depends_on:
      wmo-resource-catalogue-backend:
        condition: service_healthy
      wmo-resource-catalogue-cache:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://wmo-resource-catalogue-backend:9200/wis2-discovery-metadata"]
      interval: 5s
      retries: 3
    volumes:
      - wmo-resource-catalogue-management-data:/data
    restart: always
    command: ["/venv/bin/pywis-pubsub", "subscribe", "--config", "/app/docker/pywis-pubsub.yml", "--verbosity", "DEBUG"]
    networks:
      - wmo-resource-catalogue-net
    <<: *logging

  wmo-resource-catalogue-api:
    container_name: wmo-resource-catalogue-api
    build:
      context: ./wmo-resource-catalogue-api/
    depends_on:
      wmo-resource-catalogue-management:
        condition: service_healthy
    volumes:
      - wmo-resource-catalogue-management-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/conformance"]
      interval: 5s
      retries: 3
    env_file:
      - wmo-resource-catalogue.env
    restart: unless-stopped
    networks:
      - wmo-resource-catalogue-net
    <<: *logging

volumes:
  wmo-resource-catalogue-backend-data:
  wmo-resource-catalogue-management-data:

networks:
  wmo-resource-catalogue-net:
