server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: ${WIS2_GDC_API_URL:-http://localhost}
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 100
    map:
      url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
      attribution: 'Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    manager:
        name: TinyDB
        connection: /tmp/wis2-gdc-process-manager.db
        output_dir: /tmp/

logging:
    level: ${WIS2_GDC_LOGGING_LEVEL:-ERROR}

metadata:
    identification:
        title: ${WIS2_GDC_METADATA_IDENTIFICATION_TITLE:-WMO WIS2 Global Discovery Catalogue instance}
        description: ${WIS2_GDC_METADATA_IDENTIFICATION_DESCRIPTION:-WMO WIS2 Global Discovery Catalogue instance}
        keywords:
            - wmo
            - wis2
            - gdc
        keywords_type: theme
        terms_of_service: ${WIS2_GDC_METADATA_IDENTIFICATION_TERMS_OF_SERVICE:-https://creativecommons.org/licenses/by/4.0}
        url: ${WIS2_GDC_METADATA_IDENTIFICATION_TITLE:-https://wis2-gdc.readthedocs.io}
    license:
        name: ${WIS2_GDC_METADATA_LICENSE_NAME:-CC-BY 4.0 license}
        url: ${WIS2_GDC_METADATA_LICENSE_URL:-https://creativecommons.org/licenses/by/4.0}
    provider:
        name: ${WIS2_GDC_METADATA_PROVIDER_NAME:-GDC provider name}
        url: ${WIS2_GDC_METADATA_PROVIDER_URL:-https://github.com/wmo-im/wis2-gdc}
    contact:
        name: ${WIS2_GDC_METADATA_CONTACT_NAME:-Firstname Lastname}
        position: ${WIS2_GDC_METADATA_CONTACT_POSITION:Position name}
        address: ${WIS2_GDC_METADATA_CONTACT_ADDRESS:-Mailing Address}
        city: ${WIS2_GDC_METADATA_CONTACT_CITY:-City}
        stateorprovince: ${WIS2_GDC_METADATA_CONTACT_STATEORPROVINCE:-Administrative Area}
        postalcode: ${WIS2_GDC_METADATA_CONTACT_POSTALCODE:-Zip or Postal Code}
        country: ${WIS2_GDC_METADATA_CONTACT_COUNTRY:-Country}
        phone: ${WIS2_GDC_METADATA_CONTACT_PHONE:-+xx-xxx-xxx-xxxx}
        fax: ${WIS2_GDC_METADATA_CONTACT_FAX:-+xx-xxx-xxx-xxxx}
        email: ${WIS2_GDC_METADATA_CONTACT_EMAIL:-you@example.org}
        url: ${WIS2_GDC_METADATA_CONTACT_URL:-https://github.com/wmo-im/wis2-gdc}
        hours: ${WIS2_GDC_METADATA_CONTACT_HOURS:-Mo-Fr 08:00-17:00}
        instructions: ${WIS2_GDC_METADATA_CONTACT_INSTRUCTIONS:-During hours of service. Off on weekends.}
        role: ${WIS2_GDC_METADATA_CONTACT_ROLE:-pointOfContact}

resources:
    wis2-discovery-metadata:
        type: collection
        title: WIS2 discovery metadata
        description: WIS2 discovery metadata
        keywords: [wmo, wis2, gdc, wcmp2]
        crs:
            - CRS84
        links:
            - type: application/zip
              rel: archives
              title: Metadata archive (generated daily)
              href: ${WIS2_GDC_API_URL:-http://localhost}/wis2-discovery-metadata-archive.zip
              hreflang: en-CA
              length: -1
            - type: text/plain
              rel: related
              title: OpenMetrics
              href: ${WIS2_GDC_API_URL:-http://localhost}/wis2-gdc-metrics.txt
              hreflang: en-CA
            - type: text/plain
              rel: related
              title: Current WIS2 channels
              href: https://raw.githubusercontent.com/wmo-im/wis2-guide/refs/heads/gh-pages/gdc-all-channels-latest.txt
              hreflang: en-CA
            - type: text/html
              rel: related
              title: Analytics and monitoring dashboard
              href: ${WIS2_GDC_API_URL:-http://localhost}/grafana
              hreflang: en-CA
            - type: text/html
              rel: canonical
              title: WMO Information System (WIS) | World Meteorological Organization
              href: https://community.wmo.int/en/activity-areas/wis
              hreflang: en-CA
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: record
              name: ${WIS2_GDC_BACKEND_TYPE:-Elasticsearch}
              data: ${WIS2_GDC_BACKEND_CONNECTION:-http://wis2-gdc-backend:9200/wis2-discovery-metadata}
              id_field: id
              time_field: updated
              title_field: title

    pywcmp-wis2-wcmp2-ets:
        type: process
        processor:
            name: pywcmp.pygeoapi_plugin.WCMP2ETSProcessor

    pywcmp-wis2-wcmp2-kpi:
        type: process
        processor:
            name: pywcmp.pygeoapi_plugin.WCMP2KPIProcessor
