global:
  scrape_interval: 10s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090
- job_name: 'wis2-gdc-metrics-collector'
  static_configs:
  - targets:
    - 'wis2-gdc-metrics-collector:8006'
